---
language: python
services: docker
env:
  global:
    - ROLE_NAME: rtail
before_install:
  - sudo apt-get -qq update
install:
  - python3 -m pip install ansible
  - python3 -m pip install molecule[docker,lint]
before_script:
  - cd ../
  - git clone --depth=1 https://github.com/wate/ansible-role-repo-epel.git repo-epel
  - git clone --depth=1 https://github.com/wate/ansible-role-nodejs.git nodejs
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME
script:
  - molecule test
notifications:
  email: false
  # slack:
  #   secure: 'execute `travis encrypt "<slack_name>:<token>" --add notifications.slack -x --no-interactive`'
